---
image: ocaml/opam:alpine_ocaml-4.06.0

variables:
  OPAMYES: "yes"
  OCB_VERSION: 0.12.0
  COQ_VERSION: 8.7.2

before_script:
  - sudo apk add libffi libffi-dev
  - opam repo add opam https://opam.ocaml.org
  - opam depext -y conf-m4.1
  - opam install coq.$COQ_VERSION
  - opam install ocamlbuild.$OCB_VERSION
  - eval $(opam config env)
  - ./configure.sh
  - cd libhsem
  - ./configure.sh

test:
  script:
    - cd "$CI_PROJECT_DIR"
    - make
    - cd libhsem
    - make
    - ocamlbuild libhsem.so
    - find _build/
    - cat _build/_log


