---
image: ocaml/opam:alpine_ocaml-4.06.0

variables:
  OPAMYES: "yes"
  OCB_VERSION: 0.12.0

before_script:
  - sudo apk add libffi libffi-dev
  - opam depext -y conf-m4.1
  - eval $(opam config env)
  - opam install ocamlbuild.$OCB_VERSION
  - ./configure.sh
  - cd libhsem
  - ./configure.sh

test:
  script:
    - cd "$CI_PROJECT_DIR"
    - make
    - cd libhsem
    - make
    - ocamlbuild libhsem.so
    - find _build/


